package com.greathiit.lab.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.greathiit.lab.entity.Customer;
import com.greathiit.lab.entity.CustomerExample;
import com.greathiit.lab.page.Fenpage;

public interface CustomerMapper {
	int selectByCustId(Integer custId);
	int deleteByCustId(Integer custId);
	Customer selectCustomeByCustId(Integer custId);
	Integer selectCustIdAndCustPasswd(Customer customer);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    int countByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    int deleteByPrimaryKey(String custOid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    List<Customer> selectByExample(CustomerExample example);
    List<Customer> Fenpage(Fenpage page);
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    Customer selectByPrimaryKey(String custOid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    int updateByPrimaryKey(Customer record);
}