package com.greathiit.lab.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.greathiit.lab.entity.Equipment;
import com.greathiit.lab.entity.EquipmentExample;
import com.greathiit.lab.page.Fenpage;
import com.greathiit.lab.web.pojo.EuqAndEquType;

public interface EquipmentMapper {
	Integer selectTypeCountEquipment(Integer laborId);//计算设备类别
	Integer selectCountEquipment(Integer laborId);//计算设备总量
	List<EuqAndEquType> selectEquAllByLabId(@Param("laborId")Integer laborId,@Param("page")Fenpage page);
	EuqAndEquType selectByEqutypeId(String equtypeId);
	Integer deleteEquipmentByEquId(String equId);
	Integer selectCountEquipmentByEquId(String equId);
	Equipment selectEquipmentByEquId(String equId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    int countByExample(EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    int deleteByExample(EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    int deleteByPrimaryKey(String equOid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    int insert(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    int insertSelective(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    List<Equipment> selectByExample(EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    Equipment selectByPrimaryKey(String equOid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") Equipment record, @Param("example") EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    int updateByExample(@Param("record") Equipment record, @Param("example") EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    int updateByPrimaryKeySelective(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    int updateByPrimaryKey(Equipment record);
}