package com.greathiit.lab.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.greathiit.lab.entity.EquipmentType;
import com.greathiit.lab.entity.EquipmentTypeExample;
import com.greathiit.lab.page.Fenpage;

public interface EquipmentTypeMapper {
	List<EquipmentType> fenPage(Fenpage page);
	Integer selectEquipmentTypeById(String equtypeId);//查询数量
	EquipmentType selectEquipmentTypeByEqutypeId(String equtypeId);//返回实体
	Integer deleteequipmentTypeByEqutypeId(String equtypeId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    int countByExample(EquipmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    int deleteByExample(EquipmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    int deleteByPrimaryKey(String equtypeOid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    int insert(EquipmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    int insertSelective(EquipmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    List<EquipmentType> selectByExample(EquipmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    EquipmentType selectByPrimaryKey(String equtypeOid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") EquipmentType record, @Param("example") EquipmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    int updateByExample(@Param("record") EquipmentType record, @Param("example") EquipmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    int updateByPrimaryKeySelective(EquipmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    int updateByPrimaryKey(EquipmentType equipmentType);
}