package com.greathiit.lab.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.greathiit.lab.entity.Equipment;
import com.greathiit.lab.entity.Furniture;
import com.greathiit.lab.entity.FurnitureExample;
import com.greathiit.lab.page.Fenpage;
import com.greathiit.lab.web.pojo.FunAndFunType;

public interface FurnitureMapper {
	Integer selectTypeCountFurniture(Integer laborId);//计算设备类别
	Integer selectCountFurniture(Integer laborId);//计算设备总量
	List<FunAndFunType> selectFunAndFunTypeAllByLabId(@Param("laborId")Integer laborId,@Param("page")Fenpage page);
	FunAndFunType selectFunAndFunTypeByEqutypeId(String funtypeId);
	Integer deleteFurnitureByFunId(String funId);
	Integer selectCountFurnitureByFunId(String funId);
	Furniture selectFurnitureByFunId(String funId);
	int updateByPrimaryKey(Furniture furniture);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    int countByExample(FurnitureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    int deleteByExample(FurnitureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    int insert(Furniture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    int insertSelective(Furniture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    List<Furniture> selectByExample(FurnitureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") Furniture record, @Param("example") FurnitureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furniture
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    int updateByExample(@Param("record") Furniture record, @Param("example") FurnitureExample example);
}