package com.greathiit.lab.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.greathiit.lab.entity.EquipmentType;
import com.greathiit.lab.entity.FurnitureType;
import com.greathiit.lab.entity.FurnitureTypeExample;
import com.greathiit.lab.page.Fenpage;

public interface FurnitureTypeMapper {
	List<FurnitureType> fenPage(Fenpage page);
	Integer selectFurnitureTypeCountByFuntypeId(String funtypeId);//查询数量
	FurnitureType selectFurnitureTypeByFuntypeId(String FuntypeId);//返回实体
	Integer deleteFurnitureTypeByFuntypeId(String funtypeId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furnitureType
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    int countByExample(FurnitureTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furnitureType
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    int deleteByExample(FurnitureTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furnitureType
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    int deleteByPrimaryKey(String funtypeOid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furnitureType
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    int insert(FurnitureType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furnitureType
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    int insertSelective(FurnitureType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furnitureType
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    List<FurnitureType> selectByExample(FurnitureTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furnitureType
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    FurnitureType selectByPrimaryKey(String funtypeOid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furnitureType
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") FurnitureType record, @Param("example") FurnitureTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furnitureType
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    int updateByExample(@Param("record") FurnitureType record, @Param("example") FurnitureTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furnitureType
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    int updateByPrimaryKeySelective(FurnitureType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table furnitureType
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    int updateByPrimaryKey(FurnitureType record);
}