package com.greathiit.lab.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.greathiit.lab.entity.Laboratory;
import com.greathiit.lab.entity.LaboratoryExample;
import com.greathiit.lab.page.Fenpage;
import com.greathiit.lab.web.pojo.LaborAndCustomerAndDepartPovo;
import com.greathiit.lab.web.pojo.LaborAndEqurment;
import com.greathiit.lab.web.pojo.LaborAndSan;

public interface LaboratoryMapper {
	int deleteLabor(Integer labId);
	List<LaborAndCustomerAndDepartPovo> selectLaborAll();
	List<LaborAndCustomerAndDepartPovo> Fenpage(Fenpage page);
	LaborAndCustomerAndDepartPovo selectLaborByLaborId(Integer labId);
	List<LaborAndEqurment> selectLabIdAndName(Fenpage page);
	List<LaborAndSan> selectLabIdAndNameToLaborAndSan(Fenpage page);
	List<Laboratory>  selectLaborBylaborUser(Integer labId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Tue Apr 10 19:28:14 CST 2018
     */
    int countByExample(LaboratoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Tue Apr 10 19:28:14 CST 2018
     */
    int deleteByExample(LaboratoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Tue Apr 10 19:28:14 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Tue Apr 10 19:28:14 CST 2018
     */
    int insert(Laboratory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Tue Apr 10 19:28:14 CST 2018
     */
    int insertSelective(Laboratory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Tue Apr 10 19:28:14 CST 2018
     */
    List<Laboratory> selectByExample(LaboratoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Tue Apr 10 19:28:14 CST 2018
     */
    Laboratory selectByPrimaryKey(String id);
    Integer selectByLabId(Integer labId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Tue Apr 10 19:28:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Laboratory record, @Param("example") LaboratoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Tue Apr 10 19:28:14 CST 2018
     */
    int updateByExample(@Param("record") Laboratory record, @Param("example") LaboratoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Tue Apr 10 19:28:14 CST 2018
     */
    int updateByPrimaryKeySelective(Laboratory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Tue Apr 10 19:28:14 CST 2018
     */
    int updateByPrimaryKey(Laboratory record);
}