package com.greathiit.lab.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.greathiit.lab.entity.Sanitation;
import com.greathiit.lab.entity.SanitationExample;

public interface SanitationMapper {
	Integer selectSanCountBysanId(String sanId) ;
	Integer selectCountSanFen(Integer laborId);
	Integer selectCountSan();
	Integer seletcNewFen(@Param("laborId")Integer laborId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanitation
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    int countByExample(SanitationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanitation
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    int deleteByExample(SanitationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanitation
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    int deleteByPrimaryKey(String sanOid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanitation
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    int insert(Sanitation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanitation
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    int insertSelective(Sanitation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanitation
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    List<Sanitation> selectByExample(SanitationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanitation
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    Sanitation selectByPrimaryKey(String sanOid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanitation
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") Sanitation record, @Param("example") SanitationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanitation
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    int updateByExample(@Param("record") Sanitation record, @Param("example") SanitationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanitation
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    int updateByPrimaryKeySelective(Sanitation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanitation
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    int updateByPrimaryKey(Sanitation record);
}