package com.greathiit.lab.entity;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_oid
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private String custOid;

    @Override
	public String toString() {
		return "Customer [custOid=" + custOid + ", custId=" + custId + ", custName=" + custName + ", custPasswd="
				+ custPasswd + ", custImg=" + custImg + ", custRoot=" + custRoot + ", custPhone=" + custPhone
				+ ", custQq=" + custQq + ", custDesc=" + custDesc + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_id
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_name
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_passwd
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private String custPasswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_img
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private String custImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_root
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private String custRoot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_phone
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private String custPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_qq
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private String custQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_desc
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private String custDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_oid
     *
     * @return the value of customer.cust_oid
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getCustOid() {
        return custOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_oid
     *
     * @param custOid the value for customer.cust_oid
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setCustOid(String custOid) {
        this.custOid = custOid == null ? null : custOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_id
     *
     * @return the value of customer.cust_id
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_id
     *
     * @param custId the value for customer.cust_id
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_name
     *
     * @return the value of customer.cust_name
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_name
     *
     * @param custName the value for customer.cust_name
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_passwd
     *
     * @return the value of customer.cust_passwd
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getCustPasswd() {
        return custPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_passwd
     *
     * @param custPasswd the value for customer.cust_passwd
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setCustPasswd(String custPasswd) {
        this.custPasswd = custPasswd == null ? null : custPasswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_img
     *
     * @return the value of customer.cust_img
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getCustImg() {
        return custImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_img
     *
     * @param custImg the value for customer.cust_img
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setCustImg(String custImg) {
        this.custImg = custImg == null ? null : custImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_root
     *
     * @return the value of customer.cust_root
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getCustRoot() {
        return custRoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_root
     *
     * @param custRoot the value for customer.cust_root
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setCustRoot(String custRoot) {
        this.custRoot = custRoot == null ? null : custRoot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_phone
     *
     * @return the value of customer.cust_phone
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getCustPhone() {
        return custPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_phone
     *
     * @param custPhone the value for customer.cust_phone
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setCustPhone(String custPhone) {
        this.custPhone = custPhone == null ? null : custPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_qq
     *
     * @return the value of customer.cust_qq
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getCustQq() {
        return custQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_qq
     *
     * @param custQq the value for customer.cust_qq
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setCustQq(String custQq) {
        this.custQq = custQq == null ? null : custQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_desc
     *
     * @return the value of customer.cust_desc
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getCustDesc() {
        return custDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_desc
     *
     * @param custDesc the value for customer.cust_desc
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setCustDesc(String custDesc) {
        this.custDesc = custDesc == null ? null : custDesc.trim();
    }
}