package com.greathiit.lab.entity;

import java.util.ArrayList;
import java.util.List;

public class CustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public CustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCustOidIsNull() {
            addCriterion("cust_oid is null");
            return (Criteria) this;
        }

        public Criteria andCustOidIsNotNull() {
            addCriterion("cust_oid is not null");
            return (Criteria) this;
        }

        public Criteria andCustOidEqualTo(String value) {
            addCriterion("cust_oid =", value, "custOid");
            return (Criteria) this;
        }

        public Criteria andCustOidNotEqualTo(String value) {
            addCriterion("cust_oid <>", value, "custOid");
            return (Criteria) this;
        }

        public Criteria andCustOidGreaterThan(String value) {
            addCriterion("cust_oid >", value, "custOid");
            return (Criteria) this;
        }

        public Criteria andCustOidGreaterThanOrEqualTo(String value) {
            addCriterion("cust_oid >=", value, "custOid");
            return (Criteria) this;
        }

        public Criteria andCustOidLessThan(String value) {
            addCriterion("cust_oid <", value, "custOid");
            return (Criteria) this;
        }

        public Criteria andCustOidLessThanOrEqualTo(String value) {
            addCriterion("cust_oid <=", value, "custOid");
            return (Criteria) this;
        }

        public Criteria andCustOidLike(String value) {
            addCriterion("cust_oid like", value, "custOid");
            return (Criteria) this;
        }

        public Criteria andCustOidNotLike(String value) {
            addCriterion("cust_oid not like", value, "custOid");
            return (Criteria) this;
        }

        public Criteria andCustOidIn(List<String> values) {
            addCriterion("cust_oid in", values, "custOid");
            return (Criteria) this;
        }

        public Criteria andCustOidNotIn(List<String> values) {
            addCriterion("cust_oid not in", values, "custOid");
            return (Criteria) this;
        }

        public Criteria andCustOidBetween(String value1, String value2) {
            addCriterion("cust_oid between", value1, value2, "custOid");
            return (Criteria) this;
        }

        public Criteria andCustOidNotBetween(String value1, String value2) {
            addCriterion("cust_oid not between", value1, value2, "custOid");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNull() {
            addCriterion("cust_id is null");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNotNull() {
            addCriterion("cust_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustIdEqualTo(Integer value) {
            addCriterion("cust_id =", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotEqualTo(Integer value) {
            addCriterion("cust_id <>", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThan(Integer value) {
            addCriterion("cust_id >", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cust_id >=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThan(Integer value) {
            addCriterion("cust_id <", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThanOrEqualTo(Integer value) {
            addCriterion("cust_id <=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdIn(List<Integer> values) {
            addCriterion("cust_id in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotIn(List<Integer> values) {
            addCriterion("cust_id not in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdBetween(Integer value1, Integer value2) {
            addCriterion("cust_id between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cust_id not between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNull() {
            addCriterion("cust_name is null");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNotNull() {
            addCriterion("cust_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustNameEqualTo(String value) {
            addCriterion("cust_name =", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotEqualTo(String value) {
            addCriterion("cust_name <>", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThan(String value) {
            addCriterion("cust_name >", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThanOrEqualTo(String value) {
            addCriterion("cust_name >=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThan(String value) {
            addCriterion("cust_name <", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThanOrEqualTo(String value) {
            addCriterion("cust_name <=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLike(String value) {
            addCriterion("cust_name like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotLike(String value) {
            addCriterion("cust_name not like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameIn(List<String> values) {
            addCriterion("cust_name in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotIn(List<String> values) {
            addCriterion("cust_name not in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameBetween(String value1, String value2) {
            addCriterion("cust_name between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotBetween(String value1, String value2) {
            addCriterion("cust_name not between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustPasswdIsNull() {
            addCriterion("cust_passwd is null");
            return (Criteria) this;
        }

        public Criteria andCustPasswdIsNotNull() {
            addCriterion("cust_passwd is not null");
            return (Criteria) this;
        }

        public Criteria andCustPasswdEqualTo(String value) {
            addCriterion("cust_passwd =", value, "custPasswd");
            return (Criteria) this;
        }

        public Criteria andCustPasswdNotEqualTo(String value) {
            addCriterion("cust_passwd <>", value, "custPasswd");
            return (Criteria) this;
        }

        public Criteria andCustPasswdGreaterThan(String value) {
            addCriterion("cust_passwd >", value, "custPasswd");
            return (Criteria) this;
        }

        public Criteria andCustPasswdGreaterThanOrEqualTo(String value) {
            addCriterion("cust_passwd >=", value, "custPasswd");
            return (Criteria) this;
        }

        public Criteria andCustPasswdLessThan(String value) {
            addCriterion("cust_passwd <", value, "custPasswd");
            return (Criteria) this;
        }

        public Criteria andCustPasswdLessThanOrEqualTo(String value) {
            addCriterion("cust_passwd <=", value, "custPasswd");
            return (Criteria) this;
        }

        public Criteria andCustPasswdLike(String value) {
            addCriterion("cust_passwd like", value, "custPasswd");
            return (Criteria) this;
        }

        public Criteria andCustPasswdNotLike(String value) {
            addCriterion("cust_passwd not like", value, "custPasswd");
            return (Criteria) this;
        }

        public Criteria andCustPasswdIn(List<String> values) {
            addCriterion("cust_passwd in", values, "custPasswd");
            return (Criteria) this;
        }

        public Criteria andCustPasswdNotIn(List<String> values) {
            addCriterion("cust_passwd not in", values, "custPasswd");
            return (Criteria) this;
        }

        public Criteria andCustPasswdBetween(String value1, String value2) {
            addCriterion("cust_passwd between", value1, value2, "custPasswd");
            return (Criteria) this;
        }

        public Criteria andCustPasswdNotBetween(String value1, String value2) {
            addCriterion("cust_passwd not between", value1, value2, "custPasswd");
            return (Criteria) this;
        }

        public Criteria andCustImgIsNull() {
            addCriterion("cust_img is null");
            return (Criteria) this;
        }

        public Criteria andCustImgIsNotNull() {
            addCriterion("cust_img is not null");
            return (Criteria) this;
        }

        public Criteria andCustImgEqualTo(String value) {
            addCriterion("cust_img =", value, "custImg");
            return (Criteria) this;
        }

        public Criteria andCustImgNotEqualTo(String value) {
            addCriterion("cust_img <>", value, "custImg");
            return (Criteria) this;
        }

        public Criteria andCustImgGreaterThan(String value) {
            addCriterion("cust_img >", value, "custImg");
            return (Criteria) this;
        }

        public Criteria andCustImgGreaterThanOrEqualTo(String value) {
            addCriterion("cust_img >=", value, "custImg");
            return (Criteria) this;
        }

        public Criteria andCustImgLessThan(String value) {
            addCriterion("cust_img <", value, "custImg");
            return (Criteria) this;
        }

        public Criteria andCustImgLessThanOrEqualTo(String value) {
            addCriterion("cust_img <=", value, "custImg");
            return (Criteria) this;
        }

        public Criteria andCustImgLike(String value) {
            addCriterion("cust_img like", value, "custImg");
            return (Criteria) this;
        }

        public Criteria andCustImgNotLike(String value) {
            addCriterion("cust_img not like", value, "custImg");
            return (Criteria) this;
        }

        public Criteria andCustImgIn(List<String> values) {
            addCriterion("cust_img in", values, "custImg");
            return (Criteria) this;
        }

        public Criteria andCustImgNotIn(List<String> values) {
            addCriterion("cust_img not in", values, "custImg");
            return (Criteria) this;
        }

        public Criteria andCustImgBetween(String value1, String value2) {
            addCriterion("cust_img between", value1, value2, "custImg");
            return (Criteria) this;
        }

        public Criteria andCustImgNotBetween(String value1, String value2) {
            addCriterion("cust_img not between", value1, value2, "custImg");
            return (Criteria) this;
        }

        public Criteria andCustRootIsNull() {
            addCriterion("cust_root is null");
            return (Criteria) this;
        }

        public Criteria andCustRootIsNotNull() {
            addCriterion("cust_root is not null");
            return (Criteria) this;
        }

        public Criteria andCustRootEqualTo(String value) {
            addCriterion("cust_root =", value, "custRoot");
            return (Criteria) this;
        }

        public Criteria andCustRootNotEqualTo(String value) {
            addCriterion("cust_root <>", value, "custRoot");
            return (Criteria) this;
        }

        public Criteria andCustRootGreaterThan(String value) {
            addCriterion("cust_root >", value, "custRoot");
            return (Criteria) this;
        }

        public Criteria andCustRootGreaterThanOrEqualTo(String value) {
            addCriterion("cust_root >=", value, "custRoot");
            return (Criteria) this;
        }

        public Criteria andCustRootLessThan(String value) {
            addCriterion("cust_root <", value, "custRoot");
            return (Criteria) this;
        }

        public Criteria andCustRootLessThanOrEqualTo(String value) {
            addCriterion("cust_root <=", value, "custRoot");
            return (Criteria) this;
        }

        public Criteria andCustRootLike(String value) {
            addCriterion("cust_root like", value, "custRoot");
            return (Criteria) this;
        }

        public Criteria andCustRootNotLike(String value) {
            addCriterion("cust_root not like", value, "custRoot");
            return (Criteria) this;
        }

        public Criteria andCustRootIn(List<String> values) {
            addCriterion("cust_root in", values, "custRoot");
            return (Criteria) this;
        }

        public Criteria andCustRootNotIn(List<String> values) {
            addCriterion("cust_root not in", values, "custRoot");
            return (Criteria) this;
        }

        public Criteria andCustRootBetween(String value1, String value2) {
            addCriterion("cust_root between", value1, value2, "custRoot");
            return (Criteria) this;
        }

        public Criteria andCustRootNotBetween(String value1, String value2) {
            addCriterion("cust_root not between", value1, value2, "custRoot");
            return (Criteria) this;
        }

        public Criteria andCustPhoneIsNull() {
            addCriterion("cust_phone is null");
            return (Criteria) this;
        }

        public Criteria andCustPhoneIsNotNull() {
            addCriterion("cust_phone is not null");
            return (Criteria) this;
        }

        public Criteria andCustPhoneEqualTo(String value) {
            addCriterion("cust_phone =", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneNotEqualTo(String value) {
            addCriterion("cust_phone <>", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneGreaterThan(String value) {
            addCriterion("cust_phone >", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("cust_phone >=", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneLessThan(String value) {
            addCriterion("cust_phone <", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneLessThanOrEqualTo(String value) {
            addCriterion("cust_phone <=", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneLike(String value) {
            addCriterion("cust_phone like", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneNotLike(String value) {
            addCriterion("cust_phone not like", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneIn(List<String> values) {
            addCriterion("cust_phone in", values, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneNotIn(List<String> values) {
            addCriterion("cust_phone not in", values, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneBetween(String value1, String value2) {
            addCriterion("cust_phone between", value1, value2, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneNotBetween(String value1, String value2) {
            addCriterion("cust_phone not between", value1, value2, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustQqIsNull() {
            addCriterion("cust_qq is null");
            return (Criteria) this;
        }

        public Criteria andCustQqIsNotNull() {
            addCriterion("cust_qq is not null");
            return (Criteria) this;
        }

        public Criteria andCustQqEqualTo(String value) {
            addCriterion("cust_qq =", value, "custQq");
            return (Criteria) this;
        }

        public Criteria andCustQqNotEqualTo(String value) {
            addCriterion("cust_qq <>", value, "custQq");
            return (Criteria) this;
        }

        public Criteria andCustQqGreaterThan(String value) {
            addCriterion("cust_qq >", value, "custQq");
            return (Criteria) this;
        }

        public Criteria andCustQqGreaterThanOrEqualTo(String value) {
            addCriterion("cust_qq >=", value, "custQq");
            return (Criteria) this;
        }

        public Criteria andCustQqLessThan(String value) {
            addCriterion("cust_qq <", value, "custQq");
            return (Criteria) this;
        }

        public Criteria andCustQqLessThanOrEqualTo(String value) {
            addCriterion("cust_qq <=", value, "custQq");
            return (Criteria) this;
        }

        public Criteria andCustQqLike(String value) {
            addCriterion("cust_qq like", value, "custQq");
            return (Criteria) this;
        }

        public Criteria andCustQqNotLike(String value) {
            addCriterion("cust_qq not like", value, "custQq");
            return (Criteria) this;
        }

        public Criteria andCustQqIn(List<String> values) {
            addCriterion("cust_qq in", values, "custQq");
            return (Criteria) this;
        }

        public Criteria andCustQqNotIn(List<String> values) {
            addCriterion("cust_qq not in", values, "custQq");
            return (Criteria) this;
        }

        public Criteria andCustQqBetween(String value1, String value2) {
            addCriterion("cust_qq between", value1, value2, "custQq");
            return (Criteria) this;
        }

        public Criteria andCustQqNotBetween(String value1, String value2) {
            addCriterion("cust_qq not between", value1, value2, "custQq");
            return (Criteria) this;
        }

        public Criteria andCustDescIsNull() {
            addCriterion("cust_desc is null");
            return (Criteria) this;
        }

        public Criteria andCustDescIsNotNull() {
            addCriterion("cust_desc is not null");
            return (Criteria) this;
        }

        public Criteria andCustDescEqualTo(String value) {
            addCriterion("cust_desc =", value, "custDesc");
            return (Criteria) this;
        }

        public Criteria andCustDescNotEqualTo(String value) {
            addCriterion("cust_desc <>", value, "custDesc");
            return (Criteria) this;
        }

        public Criteria andCustDescGreaterThan(String value) {
            addCriterion("cust_desc >", value, "custDesc");
            return (Criteria) this;
        }

        public Criteria andCustDescGreaterThanOrEqualTo(String value) {
            addCriterion("cust_desc >=", value, "custDesc");
            return (Criteria) this;
        }

        public Criteria andCustDescLessThan(String value) {
            addCriterion("cust_desc <", value, "custDesc");
            return (Criteria) this;
        }

        public Criteria andCustDescLessThanOrEqualTo(String value) {
            addCriterion("cust_desc <=", value, "custDesc");
            return (Criteria) this;
        }

        public Criteria andCustDescLike(String value) {
            addCriterion("cust_desc like", value, "custDesc");
            return (Criteria) this;
        }

        public Criteria andCustDescNotLike(String value) {
            addCriterion("cust_desc not like", value, "custDesc");
            return (Criteria) this;
        }

        public Criteria andCustDescIn(List<String> values) {
            addCriterion("cust_desc in", values, "custDesc");
            return (Criteria) this;
        }

        public Criteria andCustDescNotIn(List<String> values) {
            addCriterion("cust_desc not in", values, "custDesc");
            return (Criteria) this;
        }

        public Criteria andCustDescBetween(String value1, String value2) {
            addCriterion("cust_desc between", value1, value2, "custDesc");
            return (Criteria) this;
        }

        public Criteria andCustDescNotBetween(String value1, String value2) {
            addCriterion("cust_desc not between", value1, value2, "custDesc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 19 12:06:48 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}