package com.greathiit.lab.entity;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.depart_oid
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private String departOid;

    @Override
	public String toString() {
		return "Department [departOid=" + departOid + ", departId=" + departId + ", departName=" + departName + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.depart_id
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private Integer departId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.depart_name
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private String departName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.depart_oid
     *
     * @return the value of department.depart_oid
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getDepartOid() {
        return departOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.depart_oid
     *
     * @param departOid the value for department.depart_oid
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setDepartOid(String departOid) {
        this.departOid = departOid == null ? null : departOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.depart_id
     *
     * @return the value of department.depart_id
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public Integer getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.depart_id
     *
     * @param departId the value for department.depart_id
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setDepartId(Integer departId) {
        this.departId = departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.depart_name
     *
     * @return the value of department.depart_name
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getDepartName() {
        return departName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.depart_name
     *
     * @param departName the value for department.depart_name
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setDepartName(String departName) {
        this.departName = departName == null ? null : departName.trim();
    }
}