package com.greathiit.lab.entity;

public class EquipmentType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipmentType.equtype_oid
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    private String equtypeOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipmentType.equtype_id
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    private String equtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipmentType.equtype_img
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    private String equtypeImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipmentType.equtype_name
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    private String equtypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipmentType.equtype_oid
     *
     * @return the value of equipmentType.equtype_oid
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public String getEqutypeOid() {
        return equtypeOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipmentType.equtype_oid
     *
     * @param equtypeOid the value for equipmentType.equtype_oid
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public void setEqutypeOid(String equtypeOid) {
        this.equtypeOid = equtypeOid == null ? null : equtypeOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipmentType.equtype_id
     *
     * @return the value of equipmentType.equtype_id
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public String getEqutypeId() {
        return equtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipmentType.equtype_id
     *
     * @param equtypeId the value for equipmentType.equtype_id
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public void setEqutypeId(String equtypeId) {
        this.equtypeId = equtypeId == null ? null : equtypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipmentType.equtype_img
     *
     * @return the value of equipmentType.equtype_img
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public String getEqutypeImg() {
        return equtypeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipmentType.equtype_img
     *
     * @param equtypeImg the value for equipmentType.equtype_img
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public void setEqutypeImg(String equtypeImg) {
        this.equtypeImg = equtypeImg == null ? null : equtypeImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipmentType.equtype_name
     *
     * @return the value of equipmentType.equtype_name
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public String getEqutypeName() {
        return equtypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipmentType.equtype_name
     *
     * @param equtypeName the value for equipmentType.equtype_name
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public void setEqutypeName(String equtypeName) {
        this.equtypeName = equtypeName == null ? null : equtypeName.trim();
    }
}