package com.greathiit.lab.entity;

import java.util.ArrayList;
import java.util.List;

public class EquipmentTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public EquipmentTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEqutypeOidIsNull() {
            addCriterion("equtype_oid is null");
            return (Criteria) this;
        }

        public Criteria andEqutypeOidIsNotNull() {
            addCriterion("equtype_oid is not null");
            return (Criteria) this;
        }

        public Criteria andEqutypeOidEqualTo(String value) {
            addCriterion("equtype_oid =", value, "equtypeOid");
            return (Criteria) this;
        }

        public Criteria andEqutypeOidNotEqualTo(String value) {
            addCriterion("equtype_oid <>", value, "equtypeOid");
            return (Criteria) this;
        }

        public Criteria andEqutypeOidGreaterThan(String value) {
            addCriterion("equtype_oid >", value, "equtypeOid");
            return (Criteria) this;
        }

        public Criteria andEqutypeOidGreaterThanOrEqualTo(String value) {
            addCriterion("equtype_oid >=", value, "equtypeOid");
            return (Criteria) this;
        }

        public Criteria andEqutypeOidLessThan(String value) {
            addCriterion("equtype_oid <", value, "equtypeOid");
            return (Criteria) this;
        }

        public Criteria andEqutypeOidLessThanOrEqualTo(String value) {
            addCriterion("equtype_oid <=", value, "equtypeOid");
            return (Criteria) this;
        }

        public Criteria andEqutypeOidLike(String value) {
            addCriterion("equtype_oid like", value, "equtypeOid");
            return (Criteria) this;
        }

        public Criteria andEqutypeOidNotLike(String value) {
            addCriterion("equtype_oid not like", value, "equtypeOid");
            return (Criteria) this;
        }

        public Criteria andEqutypeOidIn(List<String> values) {
            addCriterion("equtype_oid in", values, "equtypeOid");
            return (Criteria) this;
        }

        public Criteria andEqutypeOidNotIn(List<String> values) {
            addCriterion("equtype_oid not in", values, "equtypeOid");
            return (Criteria) this;
        }

        public Criteria andEqutypeOidBetween(String value1, String value2) {
            addCriterion("equtype_oid between", value1, value2, "equtypeOid");
            return (Criteria) this;
        }

        public Criteria andEqutypeOidNotBetween(String value1, String value2) {
            addCriterion("equtype_oid not between", value1, value2, "equtypeOid");
            return (Criteria) this;
        }

        public Criteria andEqutypeIdIsNull() {
            addCriterion("equtype_id is null");
            return (Criteria) this;
        }

        public Criteria andEqutypeIdIsNotNull() {
            addCriterion("equtype_id is not null");
            return (Criteria) this;
        }

        public Criteria andEqutypeIdEqualTo(String value) {
            addCriterion("equtype_id =", value, "equtypeId");
            return (Criteria) this;
        }

        public Criteria andEqutypeIdNotEqualTo(String value) {
            addCriterion("equtype_id <>", value, "equtypeId");
            return (Criteria) this;
        }

        public Criteria andEqutypeIdGreaterThan(String value) {
            addCriterion("equtype_id >", value, "equtypeId");
            return (Criteria) this;
        }

        public Criteria andEqutypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("equtype_id >=", value, "equtypeId");
            return (Criteria) this;
        }

        public Criteria andEqutypeIdLessThan(String value) {
            addCriterion("equtype_id <", value, "equtypeId");
            return (Criteria) this;
        }

        public Criteria andEqutypeIdLessThanOrEqualTo(String value) {
            addCriterion("equtype_id <=", value, "equtypeId");
            return (Criteria) this;
        }

        public Criteria andEqutypeIdLike(String value) {
            addCriterion("equtype_id like", value, "equtypeId");
            return (Criteria) this;
        }

        public Criteria andEqutypeIdNotLike(String value) {
            addCriterion("equtype_id not like", value, "equtypeId");
            return (Criteria) this;
        }

        public Criteria andEqutypeIdIn(List<String> values) {
            addCriterion("equtype_id in", values, "equtypeId");
            return (Criteria) this;
        }

        public Criteria andEqutypeIdNotIn(List<String> values) {
            addCriterion("equtype_id not in", values, "equtypeId");
            return (Criteria) this;
        }

        public Criteria andEqutypeIdBetween(String value1, String value2) {
            addCriterion("equtype_id between", value1, value2, "equtypeId");
            return (Criteria) this;
        }

        public Criteria andEqutypeIdNotBetween(String value1, String value2) {
            addCriterion("equtype_id not between", value1, value2, "equtypeId");
            return (Criteria) this;
        }

        public Criteria andEqutypeImgIsNull() {
            addCriterion("equtype_img is null");
            return (Criteria) this;
        }

        public Criteria andEqutypeImgIsNotNull() {
            addCriterion("equtype_img is not null");
            return (Criteria) this;
        }

        public Criteria andEqutypeImgEqualTo(String value) {
            addCriterion("equtype_img =", value, "equtypeImg");
            return (Criteria) this;
        }

        public Criteria andEqutypeImgNotEqualTo(String value) {
            addCriterion("equtype_img <>", value, "equtypeImg");
            return (Criteria) this;
        }

        public Criteria andEqutypeImgGreaterThan(String value) {
            addCriterion("equtype_img >", value, "equtypeImg");
            return (Criteria) this;
        }

        public Criteria andEqutypeImgGreaterThanOrEqualTo(String value) {
            addCriterion("equtype_img >=", value, "equtypeImg");
            return (Criteria) this;
        }

        public Criteria andEqutypeImgLessThan(String value) {
            addCriterion("equtype_img <", value, "equtypeImg");
            return (Criteria) this;
        }

        public Criteria andEqutypeImgLessThanOrEqualTo(String value) {
            addCriterion("equtype_img <=", value, "equtypeImg");
            return (Criteria) this;
        }

        public Criteria andEqutypeImgLike(String value) {
            addCriterion("equtype_img like", value, "equtypeImg");
            return (Criteria) this;
        }

        public Criteria andEqutypeImgNotLike(String value) {
            addCriterion("equtype_img not like", value, "equtypeImg");
            return (Criteria) this;
        }

        public Criteria andEqutypeImgIn(List<String> values) {
            addCriterion("equtype_img in", values, "equtypeImg");
            return (Criteria) this;
        }

        public Criteria andEqutypeImgNotIn(List<String> values) {
            addCriterion("equtype_img not in", values, "equtypeImg");
            return (Criteria) this;
        }

        public Criteria andEqutypeImgBetween(String value1, String value2) {
            addCriterion("equtype_img between", value1, value2, "equtypeImg");
            return (Criteria) this;
        }

        public Criteria andEqutypeImgNotBetween(String value1, String value2) {
            addCriterion("equtype_img not between", value1, value2, "equtypeImg");
            return (Criteria) this;
        }

        public Criteria andEqutypeNameIsNull() {
            addCriterion("equtype_name is null");
            return (Criteria) this;
        }

        public Criteria andEqutypeNameIsNotNull() {
            addCriterion("equtype_name is not null");
            return (Criteria) this;
        }

        public Criteria andEqutypeNameEqualTo(String value) {
            addCriterion("equtype_name =", value, "equtypeName");
            return (Criteria) this;
        }

        public Criteria andEqutypeNameNotEqualTo(String value) {
            addCriterion("equtype_name <>", value, "equtypeName");
            return (Criteria) this;
        }

        public Criteria andEqutypeNameGreaterThan(String value) {
            addCriterion("equtype_name >", value, "equtypeName");
            return (Criteria) this;
        }

        public Criteria andEqutypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("equtype_name >=", value, "equtypeName");
            return (Criteria) this;
        }

        public Criteria andEqutypeNameLessThan(String value) {
            addCriterion("equtype_name <", value, "equtypeName");
            return (Criteria) this;
        }

        public Criteria andEqutypeNameLessThanOrEqualTo(String value) {
            addCriterion("equtype_name <=", value, "equtypeName");
            return (Criteria) this;
        }

        public Criteria andEqutypeNameLike(String value) {
            addCriterion("equtype_name like", value, "equtypeName");
            return (Criteria) this;
        }

        public Criteria andEqutypeNameNotLike(String value) {
            addCriterion("equtype_name not like", value, "equtypeName");
            return (Criteria) this;
        }

        public Criteria andEqutypeNameIn(List<String> values) {
            addCriterion("equtype_name in", values, "equtypeName");
            return (Criteria) this;
        }

        public Criteria andEqutypeNameNotIn(List<String> values) {
            addCriterion("equtype_name not in", values, "equtypeName");
            return (Criteria) this;
        }

        public Criteria andEqutypeNameBetween(String value1, String value2) {
            addCriterion("equtype_name between", value1, value2, "equtypeName");
            return (Criteria) this;
        }

        public Criteria andEqutypeNameNotBetween(String value1, String value2) {
            addCriterion("equtype_name not between", value1, value2, "equtypeName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipmentType
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 22 15:49:53 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipmentType
     *
     * @mbggenerated Sun Apr 22 15:49:53 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}