package com.greathiit.lab.entity;

import java.util.ArrayList;
import java.util.List;

public class EquipmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    public EquipmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEquOidIsNull() {
            addCriterion("equ_oid is null");
            return (Criteria) this;
        }

        public Criteria andEquOidIsNotNull() {
            addCriterion("equ_oid is not null");
            return (Criteria) this;
        }

        public Criteria andEquOidEqualTo(String value) {
            addCriterion("equ_oid =", value, "equOid");
            return (Criteria) this;
        }

        public Criteria andEquOidNotEqualTo(String value) {
            addCriterion("equ_oid <>", value, "equOid");
            return (Criteria) this;
        }

        public Criteria andEquOidGreaterThan(String value) {
            addCriterion("equ_oid >", value, "equOid");
            return (Criteria) this;
        }

        public Criteria andEquOidGreaterThanOrEqualTo(String value) {
            addCriterion("equ_oid >=", value, "equOid");
            return (Criteria) this;
        }

        public Criteria andEquOidLessThan(String value) {
            addCriterion("equ_oid <", value, "equOid");
            return (Criteria) this;
        }

        public Criteria andEquOidLessThanOrEqualTo(String value) {
            addCriterion("equ_oid <=", value, "equOid");
            return (Criteria) this;
        }

        public Criteria andEquOidLike(String value) {
            addCriterion("equ_oid like", value, "equOid");
            return (Criteria) this;
        }

        public Criteria andEquOidNotLike(String value) {
            addCriterion("equ_oid not like", value, "equOid");
            return (Criteria) this;
        }

        public Criteria andEquOidIn(List<String> values) {
            addCriterion("equ_oid in", values, "equOid");
            return (Criteria) this;
        }

        public Criteria andEquOidNotIn(List<String> values) {
            addCriterion("equ_oid not in", values, "equOid");
            return (Criteria) this;
        }

        public Criteria andEquOidBetween(String value1, String value2) {
            addCriterion("equ_oid between", value1, value2, "equOid");
            return (Criteria) this;
        }

        public Criteria andEquOidNotBetween(String value1, String value2) {
            addCriterion("equ_oid not between", value1, value2, "equOid");
            return (Criteria) this;
        }

        public Criteria andEquIdIsNull() {
            addCriterion("equ_id is null");
            return (Criteria) this;
        }

        public Criteria andEquIdIsNotNull() {
            addCriterion("equ_id is not null");
            return (Criteria) this;
        }

        public Criteria andEquIdEqualTo(String value) {
            addCriterion("equ_id =", value, "equId");
            return (Criteria) this;
        }

        public Criteria andEquIdNotEqualTo(String value) {
            addCriterion("equ_id <>", value, "equId");
            return (Criteria) this;
        }

        public Criteria andEquIdGreaterThan(String value) {
            addCriterion("equ_id >", value, "equId");
            return (Criteria) this;
        }

        public Criteria andEquIdGreaterThanOrEqualTo(String value) {
            addCriterion("equ_id >=", value, "equId");
            return (Criteria) this;
        }

        public Criteria andEquIdLessThan(String value) {
            addCriterion("equ_id <", value, "equId");
            return (Criteria) this;
        }

        public Criteria andEquIdLessThanOrEqualTo(String value) {
            addCriterion("equ_id <=", value, "equId");
            return (Criteria) this;
        }

        public Criteria andEquIdLike(String value) {
            addCriterion("equ_id like", value, "equId");
            return (Criteria) this;
        }

        public Criteria andEquIdNotLike(String value) {
            addCriterion("equ_id not like", value, "equId");
            return (Criteria) this;
        }

        public Criteria andEquIdIn(List<String> values) {
            addCriterion("equ_id in", values, "equId");
            return (Criteria) this;
        }

        public Criteria andEquIdNotIn(List<String> values) {
            addCriterion("equ_id not in", values, "equId");
            return (Criteria) this;
        }

        public Criteria andEquIdBetween(String value1, String value2) {
            addCriterion("equ_id between", value1, value2, "equId");
            return (Criteria) this;
        }

        public Criteria andEquIdNotBetween(String value1, String value2) {
            addCriterion("equ_id not between", value1, value2, "equId");
            return (Criteria) this;
        }

        public Criteria andEquCountIsNull() {
            addCriterion("equ_count is null");
            return (Criteria) this;
        }

        public Criteria andEquCountIsNotNull() {
            addCriterion("equ_count is not null");
            return (Criteria) this;
        }

        public Criteria andEquCountEqualTo(Integer value) {
            addCriterion("equ_count =", value, "equCount");
            return (Criteria) this;
        }

        public Criteria andEquCountNotEqualTo(Integer value) {
            addCriterion("equ_count <>", value, "equCount");
            return (Criteria) this;
        }

        public Criteria andEquCountGreaterThan(Integer value) {
            addCriterion("equ_count >", value, "equCount");
            return (Criteria) this;
        }

        public Criteria andEquCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("equ_count >=", value, "equCount");
            return (Criteria) this;
        }

        public Criteria andEquCountLessThan(Integer value) {
            addCriterion("equ_count <", value, "equCount");
            return (Criteria) this;
        }

        public Criteria andEquCountLessThanOrEqualTo(Integer value) {
            addCriterion("equ_count <=", value, "equCount");
            return (Criteria) this;
        }

        public Criteria andEquCountIn(List<Integer> values) {
            addCriterion("equ_count in", values, "equCount");
            return (Criteria) this;
        }

        public Criteria andEquCountNotIn(List<Integer> values) {
            addCriterion("equ_count not in", values, "equCount");
            return (Criteria) this;
        }

        public Criteria andEquCountBetween(Integer value1, Integer value2) {
            addCriterion("equ_count between", value1, value2, "equCount");
            return (Criteria) this;
        }

        public Criteria andEquCountNotBetween(Integer value1, Integer value2) {
            addCriterion("equ_count not between", value1, value2, "equCount");
            return (Criteria) this;
        }

        public Criteria andLaborIdIsNull() {
            addCriterion("labor_id is null");
            return (Criteria) this;
        }

        public Criteria andLaborIdIsNotNull() {
            addCriterion("labor_id is not null");
            return (Criteria) this;
        }

        public Criteria andLaborIdEqualTo(Integer value) {
            addCriterion("labor_id =", value, "laborId");
            return (Criteria) this;
        }

        public Criteria andLaborIdNotEqualTo(Integer value) {
            addCriterion("labor_id <>", value, "laborId");
            return (Criteria) this;
        }

        public Criteria andLaborIdGreaterThan(Integer value) {
            addCriterion("labor_id >", value, "laborId");
            return (Criteria) this;
        }

        public Criteria andLaborIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("labor_id >=", value, "laborId");
            return (Criteria) this;
        }

        public Criteria andLaborIdLessThan(Integer value) {
            addCriterion("labor_id <", value, "laborId");
            return (Criteria) this;
        }

        public Criteria andLaborIdLessThanOrEqualTo(Integer value) {
            addCriterion("labor_id <=", value, "laborId");
            return (Criteria) this;
        }

        public Criteria andLaborIdIn(List<Integer> values) {
            addCriterion("labor_id in", values, "laborId");
            return (Criteria) this;
        }

        public Criteria andLaborIdNotIn(List<Integer> values) {
            addCriterion("labor_id not in", values, "laborId");
            return (Criteria) this;
        }

        public Criteria andLaborIdBetween(Integer value1, Integer value2) {
            addCriterion("labor_id between", value1, value2, "laborId");
            return (Criteria) this;
        }

        public Criteria andLaborIdNotBetween(Integer value1, Integer value2) {
            addCriterion("labor_id not between", value1, value2, "laborId");
            return (Criteria) this;
        }

        public Criteria andEtypeIdIsNull() {
            addCriterion("etype_id is null");
            return (Criteria) this;
        }

        public Criteria andEtypeIdIsNotNull() {
            addCriterion("etype_id is not null");
            return (Criteria) this;
        }

        public Criteria andEtypeIdEqualTo(String value) {
            addCriterion("etype_id =", value, "etypeId");
            return (Criteria) this;
        }

        public Criteria andEtypeIdNotEqualTo(String value) {
            addCriterion("etype_id <>", value, "etypeId");
            return (Criteria) this;
        }

        public Criteria andEtypeIdGreaterThan(String value) {
            addCriterion("etype_id >", value, "etypeId");
            return (Criteria) this;
        }

        public Criteria andEtypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("etype_id >=", value, "etypeId");
            return (Criteria) this;
        }

        public Criteria andEtypeIdLessThan(String value) {
            addCriterion("etype_id <", value, "etypeId");
            return (Criteria) this;
        }

        public Criteria andEtypeIdLessThanOrEqualTo(String value) {
            addCriterion("etype_id <=", value, "etypeId");
            return (Criteria) this;
        }

        public Criteria andEtypeIdLike(String value) {
            addCriterion("etype_id like", value, "etypeId");
            return (Criteria) this;
        }

        public Criteria andEtypeIdNotLike(String value) {
            addCriterion("etype_id not like", value, "etypeId");
            return (Criteria) this;
        }

        public Criteria andEtypeIdIn(List<String> values) {
            addCriterion("etype_id in", values, "etypeId");
            return (Criteria) this;
        }

        public Criteria andEtypeIdNotIn(List<String> values) {
            addCriterion("etype_id not in", values, "etypeId");
            return (Criteria) this;
        }

        public Criteria andEtypeIdBetween(String value1, String value2) {
            addCriterion("etype_id between", value1, value2, "etypeId");
            return (Criteria) this;
        }

        public Criteria andEtypeIdNotBetween(String value1, String value2) {
            addCriterion("etype_id not between", value1, value2, "etypeId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipment
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 22 09:19:18 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipment
     *
     * @mbggenerated Sun Apr 22 09:19:18 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}