package com.greathiit.lab.entity;

public class FurnitureType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column furnitureType.funtype_oid
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    private String funtypeOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column furnitureType.funtype_id
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    private String funtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column furnitureType.funtype_img
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    private String funtypeImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column furnitureType.funtype_name
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    private String funtypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column furnitureType.funtype_oid
     *
     * @return the value of furnitureType.funtype_oid
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public String getFuntypeOid() {
        return funtypeOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column furnitureType.funtype_oid
     *
     * @param funtypeOid the value for furnitureType.funtype_oid
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public void setFuntypeOid(String funtypeOid) {
        this.funtypeOid = funtypeOid == null ? null : funtypeOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column furnitureType.funtype_id
     *
     * @return the value of furnitureType.funtype_id
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public String getFuntypeId() {
        return funtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column furnitureType.funtype_id
     *
     * @param funtypeId the value for furnitureType.funtype_id
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public void setFuntypeId(String funtypeId) {
        this.funtypeId = funtypeId == null ? null : funtypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column furnitureType.funtype_img
     *
     * @return the value of furnitureType.funtype_img
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public String getFuntypeImg() {
        return funtypeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column furnitureType.funtype_img
     *
     * @param funtypeImg the value for furnitureType.funtype_img
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public void setFuntypeImg(String funtypeImg) {
        this.funtypeImg = funtypeImg == null ? null : funtypeImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column furnitureType.funtype_name
     *
     * @return the value of furnitureType.funtype_name
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public String getFuntypeName() {
        return funtypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column furnitureType.funtype_name
     *
     * @param funtypeName the value for furnitureType.funtype_name
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public void setFuntypeName(String funtypeName) {
        this.funtypeName = funtypeName == null ? null : funtypeName.trim();
    }
}