package com.greathiit.lab.entity;

public class Furniture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column furniture.fun_oid
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    private String funOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column furniture.fun_id
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    private String funId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column furniture.fun_count
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    private Integer funCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column furniture.labor_id
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    private Integer laborId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column furniture.funtype_id
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    private String funtypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column furniture.fun_oid
     *
     * @return the value of furniture.fun_oid
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public String getFunOid() {
        return funOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column furniture.fun_oid
     *
     * @param funOid the value for furniture.fun_oid
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public void setFunOid(String funOid) {
        this.funOid = funOid == null ? null : funOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column furniture.fun_id
     *
     * @return the value of furniture.fun_id
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public String getFunId() {
        return funId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column furniture.fun_id
     *
     * @param funId the value for furniture.fun_id
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public void setFunId(String funId) {
        this.funId = funId == null ? null : funId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column furniture.fun_count
     *
     * @return the value of furniture.fun_count
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public Integer getFunCount() {
        return funCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column furniture.fun_count
     *
     * @param funCount the value for furniture.fun_count
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public void setFunCount(Integer funCount) {
        this.funCount = funCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column furniture.labor_id
     *
     * @return the value of furniture.labor_id
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public Integer getLaborId() {
        return laborId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column furniture.labor_id
     *
     * @param laborId the value for furniture.labor_id
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public void setLaborId(Integer laborId) {
        this.laborId = laborId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column furniture.funtype_id
     *
     * @return the value of furniture.funtype_id
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public String getFuntypeId() {
        return funtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column furniture.funtype_id
     *
     * @param funtypeId the value for furniture.funtype_id
     *
     * @mbggenerated Mon Apr 23 17:37:39 CST 2018
     */
    public void setFuntypeId(String funtypeId) {
        this.funtypeId = funtypeId == null ? null : funtypeId.trim();
    }
}