package com.greathiit.lab.entity;

import java.util.ArrayList;
import java.util.List;

public class LaboratoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public LaboratoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLabIdIsNull() {
            addCriterion("lab_id is null");
            return (Criteria) this;
        }

        public Criteria andLabIdIsNotNull() {
            addCriterion("lab_id is not null");
            return (Criteria) this;
        }

        public Criteria andLabIdEqualTo(Integer value) {
            addCriterion("lab_id =", value, "labId");
            return (Criteria) this;
        }

        public Criteria andLabIdNotEqualTo(Integer value) {
            addCriterion("lab_id <>", value, "labId");
            return (Criteria) this;
        }

        public Criteria andLabIdGreaterThan(Integer value) {
            addCriterion("lab_id >", value, "labId");
            return (Criteria) this;
        }

        public Criteria andLabIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("lab_id >=", value, "labId");
            return (Criteria) this;
        }

        public Criteria andLabIdLessThan(Integer value) {
            addCriterion("lab_id <", value, "labId");
            return (Criteria) this;
        }

        public Criteria andLabIdLessThanOrEqualTo(Integer value) {
            addCriterion("lab_id <=", value, "labId");
            return (Criteria) this;
        }

        public Criteria andLabIdIn(List<Integer> values) {
            addCriterion("lab_id in", values, "labId");
            return (Criteria) this;
        }

        public Criteria andLabIdNotIn(List<Integer> values) {
            addCriterion("lab_id not in", values, "labId");
            return (Criteria) this;
        }

        public Criteria andLabIdBetween(Integer value1, Integer value2) {
            addCriterion("lab_id between", value1, value2, "labId");
            return (Criteria) this;
        }

        public Criteria andLabIdNotBetween(Integer value1, Integer value2) {
            addCriterion("lab_id not between", value1, value2, "labId");
            return (Criteria) this;
        }

        public Criteria andLabRoomIsNull() {
            addCriterion("lab_room is null");
            return (Criteria) this;
        }

        public Criteria andLabRoomIsNotNull() {
            addCriterion("lab_room is not null");
            return (Criteria) this;
        }

        public Criteria andLabRoomEqualTo(String value) {
            addCriterion("lab_room =", value, "labRoom");
            return (Criteria) this;
        }

        public Criteria andLabRoomNotEqualTo(String value) {
            addCriterion("lab_room <>", value, "labRoom");
            return (Criteria) this;
        }

        public Criteria andLabRoomGreaterThan(String value) {
            addCriterion("lab_room >", value, "labRoom");
            return (Criteria) this;
        }

        public Criteria andLabRoomGreaterThanOrEqualTo(String value) {
            addCriterion("lab_room >=", value, "labRoom");
            return (Criteria) this;
        }

        public Criteria andLabRoomLessThan(String value) {
            addCriterion("lab_room <", value, "labRoom");
            return (Criteria) this;
        }

        public Criteria andLabRoomLessThanOrEqualTo(String value) {
            addCriterion("lab_room <=", value, "labRoom");
            return (Criteria) this;
        }

        public Criteria andLabRoomLike(String value) {
            addCriterion("lab_room like", value, "labRoom");
            return (Criteria) this;
        }

        public Criteria andLabRoomNotLike(String value) {
            addCriterion("lab_room not like", value, "labRoom");
            return (Criteria) this;
        }

        public Criteria andLabRoomIn(List<String> values) {
            addCriterion("lab_room in", values, "labRoom");
            return (Criteria) this;
        }

        public Criteria andLabRoomNotIn(List<String> values) {
            addCriterion("lab_room not in", values, "labRoom");
            return (Criteria) this;
        }

        public Criteria andLabRoomBetween(String value1, String value2) {
            addCriterion("lab_room between", value1, value2, "labRoom");
            return (Criteria) this;
        }

        public Criteria andLabRoomNotBetween(String value1, String value2) {
            addCriterion("lab_room not between", value1, value2, "labRoom");
            return (Criteria) this;
        }

        public Criteria andLabNameIsNull() {
            addCriterion("lab_name is null");
            return (Criteria) this;
        }

        public Criteria andLabNameIsNotNull() {
            addCriterion("lab_name is not null");
            return (Criteria) this;
        }

        public Criteria andLabNameEqualTo(String value) {
            addCriterion("lab_name =", value, "labName");
            return (Criteria) this;
        }

        public Criteria andLabNameNotEqualTo(String value) {
            addCriterion("lab_name <>", value, "labName");
            return (Criteria) this;
        }

        public Criteria andLabNameGreaterThan(String value) {
            addCriterion("lab_name >", value, "labName");
            return (Criteria) this;
        }

        public Criteria andLabNameGreaterThanOrEqualTo(String value) {
            addCriterion("lab_name >=", value, "labName");
            return (Criteria) this;
        }

        public Criteria andLabNameLessThan(String value) {
            addCriterion("lab_name <", value, "labName");
            return (Criteria) this;
        }

        public Criteria andLabNameLessThanOrEqualTo(String value) {
            addCriterion("lab_name <=", value, "labName");
            return (Criteria) this;
        }

        public Criteria andLabNameLike(String value) {
            addCriterion("lab_name like", value, "labName");
            return (Criteria) this;
        }

        public Criteria andLabNameNotLike(String value) {
            addCriterion("lab_name not like", value, "labName");
            return (Criteria) this;
        }

        public Criteria andLabNameIn(List<String> values) {
            addCriterion("lab_name in", values, "labName");
            return (Criteria) this;
        }

        public Criteria andLabNameNotIn(List<String> values) {
            addCriterion("lab_name not in", values, "labName");
            return (Criteria) this;
        }

        public Criteria andLabNameBetween(String value1, String value2) {
            addCriterion("lab_name between", value1, value2, "labName");
            return (Criteria) this;
        }

        public Criteria andLabNameNotBetween(String value1, String value2) {
            addCriterion("lab_name not between", value1, value2, "labName");
            return (Criteria) this;
        }

        public Criteria andLabUserIsNull() {
            addCriterion("lab_user is null");
            return (Criteria) this;
        }

        public Criteria andLabUserIsNotNull() {
            addCriterion("lab_user is not null");
            return (Criteria) this;
        }

        public Criteria andLabUserEqualTo(Integer value) {
            addCriterion("lab_user =", value, "labUser");
            return (Criteria) this;
        }

        public Criteria andLabUserNotEqualTo(Integer value) {
            addCriterion("lab_user <>", value, "labUser");
            return (Criteria) this;
        }

        public Criteria andLabUserGreaterThan(Integer value) {
            addCriterion("lab_user >", value, "labUser");
            return (Criteria) this;
        }

        public Criteria andLabUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("lab_user >=", value, "labUser");
            return (Criteria) this;
        }

        public Criteria andLabUserLessThan(Integer value) {
            addCriterion("lab_user <", value, "labUser");
            return (Criteria) this;
        }

        public Criteria andLabUserLessThanOrEqualTo(Integer value) {
            addCriterion("lab_user <=", value, "labUser");
            return (Criteria) this;
        }

        public Criteria andLabUserIn(List<Integer> values) {
            addCriterion("lab_user in", values, "labUser");
            return (Criteria) this;
        }

        public Criteria andLabUserNotIn(List<Integer> values) {
            addCriterion("lab_user not in", values, "labUser");
            return (Criteria) this;
        }

        public Criteria andLabUserBetween(Integer value1, Integer value2) {
            addCriterion("lab_user between", value1, value2, "labUser");
            return (Criteria) this;
        }

        public Criteria andLabUserNotBetween(Integer value1, Integer value2) {
            addCriterion("lab_user not between", value1, value2, "labUser");
            return (Criteria) this;
        }

        public Criteria andLabDepartIsNull() {
            addCriterion("lab_depart is null");
            return (Criteria) this;
        }

        public Criteria andLabDepartIsNotNull() {
            addCriterion("lab_depart is not null");
            return (Criteria) this;
        }

        public Criteria andLabDepartEqualTo(Integer value) {
            addCriterion("lab_depart =", value, "labDepart");
            return (Criteria) this;
        }

        public Criteria andLabDepartNotEqualTo(Integer value) {
            addCriterion("lab_depart <>", value, "labDepart");
            return (Criteria) this;
        }

        public Criteria andLabDepartGreaterThan(Integer value) {
            addCriterion("lab_depart >", value, "labDepart");
            return (Criteria) this;
        }

        public Criteria andLabDepartGreaterThanOrEqualTo(Integer value) {
            addCriterion("lab_depart >=", value, "labDepart");
            return (Criteria) this;
        }

        public Criteria andLabDepartLessThan(Integer value) {
            addCriterion("lab_depart <", value, "labDepart");
            return (Criteria) this;
        }

        public Criteria andLabDepartLessThanOrEqualTo(Integer value) {
            addCriterion("lab_depart <=", value, "labDepart");
            return (Criteria) this;
        }

        public Criteria andLabDepartIn(List<Integer> values) {
            addCriterion("lab_depart in", values, "labDepart");
            return (Criteria) this;
        }

        public Criteria andLabDepartNotIn(List<Integer> values) {
            addCriterion("lab_depart not in", values, "labDepart");
            return (Criteria) this;
        }

        public Criteria andLabDepartBetween(Integer value1, Integer value2) {
            addCriterion("lab_depart between", value1, value2, "labDepart");
            return (Criteria) this;
        }

        public Criteria andLabDepartNotBetween(Integer value1, Integer value2) {
            addCriterion("lab_depart not between", value1, value2, "labDepart");
            return (Criteria) this;
        }

        public Criteria andLabUseIsNull() {
            addCriterion("lab_use is null");
            return (Criteria) this;
        }

        public Criteria andLabUseIsNotNull() {
            addCriterion("lab_use is not null");
            return (Criteria) this;
        }

        public Criteria andLabUseEqualTo(String value) {
            addCriterion("lab_use =", value, "labUse");
            return (Criteria) this;
        }

        public Criteria andLabUseNotEqualTo(String value) {
            addCriterion("lab_use <>", value, "labUse");
            return (Criteria) this;
        }

        public Criteria andLabUseGreaterThan(String value) {
            addCriterion("lab_use >", value, "labUse");
            return (Criteria) this;
        }

        public Criteria andLabUseGreaterThanOrEqualTo(String value) {
            addCriterion("lab_use >=", value, "labUse");
            return (Criteria) this;
        }

        public Criteria andLabUseLessThan(String value) {
            addCriterion("lab_use <", value, "labUse");
            return (Criteria) this;
        }

        public Criteria andLabUseLessThanOrEqualTo(String value) {
            addCriterion("lab_use <=", value, "labUse");
            return (Criteria) this;
        }

        public Criteria andLabUseLike(String value) {
            addCriterion("lab_use like", value, "labUse");
            return (Criteria) this;
        }

        public Criteria andLabUseNotLike(String value) {
            addCriterion("lab_use not like", value, "labUse");
            return (Criteria) this;
        }

        public Criteria andLabUseIn(List<String> values) {
            addCriterion("lab_use in", values, "labUse");
            return (Criteria) this;
        }

        public Criteria andLabUseNotIn(List<String> values) {
            addCriterion("lab_use not in", values, "labUse");
            return (Criteria) this;
        }

        public Criteria andLabUseBetween(String value1, String value2) {
            addCriterion("lab_use between", value1, value2, "labUse");
            return (Criteria) this;
        }

        public Criteria andLabUseNotBetween(String value1, String value2) {
            addCriterion("lab_use not between", value1, value2, "labUse");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table laboratory
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 19 12:06:48 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table laboratory
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}