package com.greathiit.lab.entity;

public class Laboratory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laboratory.id
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laboratory.lab_id
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private Integer labId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laboratory.lab_room
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private String labRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laboratory.lab_name
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private String labName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laboratory.lab_user
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private Integer labUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laboratory.lab_depart
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private Integer labDepart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laboratory.lab_use
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    private String labUse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laboratory.id
     *
     * @return the value of laboratory.id
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laboratory.id
     *
     * @param id the value for laboratory.id
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laboratory.lab_id
     *
     * @return the value of laboratory.lab_id
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public Integer getLabId() {
        return labId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laboratory.lab_id
     *
     * @param labId the value for laboratory.lab_id
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setLabId(Integer labId) {
        this.labId = labId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laboratory.lab_room
     *
     * @return the value of laboratory.lab_room
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getLabRoom() {
        return labRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laboratory.lab_room
     *
     * @param labRoom the value for laboratory.lab_room
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setLabRoom(String labRoom) {
        this.labRoom = labRoom == null ? null : labRoom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laboratory.lab_name
     *
     * @return the value of laboratory.lab_name
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getLabName() {
        return labName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laboratory.lab_name
     *
     * @param labName the value for laboratory.lab_name
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setLabName(String labName) {
        this.labName = labName == null ? null : labName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laboratory.lab_user
     *
     * @return the value of laboratory.lab_user
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public Integer getLabUser() {
        return labUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laboratory.lab_user
     *
     * @param labUser the value for laboratory.lab_user
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setLabUser(Integer labUser) {
        this.labUser = labUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laboratory.lab_depart
     *
     * @return the value of laboratory.lab_depart
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public Integer getLabDepart() {
        return labDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laboratory.lab_depart
     *
     * @param labDepart the value for laboratory.lab_depart
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setLabDepart(Integer labDepart) {
        this.labDepart = labDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laboratory.lab_use
     *
     * @return the value of laboratory.lab_use
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public String getLabUse() {
        return labUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laboratory.lab_use
     *
     * @param labUse the value for laboratory.lab_use
     *
     * @mbggenerated Thu Apr 19 12:06:48 CST 2018
     */
    public void setLabUse(String labUse) {
        this.labUse = labUse == null ? null : labUse.trim();
    }
}