package com.greathiit.lab.entity;

import java.util.Date;

public class Sanitation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sanitation.san_oid
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    private String sanOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sanitation.san_id
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    private String sanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sanitation.san_fen
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    private Integer sanFen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sanitation.san_date
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    private Date sanDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sanitation.labor_id
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    private Integer laborId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sanitation.san_desc
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    private String sanDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sanitation.san_oid
     *
     * @return the value of sanitation.san_oid
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    public String getSanOid() {
        return sanOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sanitation.san_oid
     *
     * @param sanOid the value for sanitation.san_oid
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    public void setSanOid(String sanOid) {
        this.sanOid = sanOid == null ? null : sanOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sanitation.san_id
     *
     * @return the value of sanitation.san_id
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    public String getSanId() {
        return sanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sanitation.san_id
     *
     * @param sanId the value for sanitation.san_id
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    public void setSanId(String sanId) {
        this.sanId = sanId == null ? null : sanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sanitation.san_fen
     *
     * @return the value of sanitation.san_fen
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    public Integer getSanFen() {
        return sanFen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sanitation.san_fen
     *
     * @param sanFen the value for sanitation.san_fen
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    public void setSanFen(Integer sanFen) {
        this.sanFen = sanFen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sanitation.san_date
     *
     * @return the value of sanitation.san_date
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    public Date getSanDate() {
        return sanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sanitation.san_date
     *
     * @param sanDate the value for sanitation.san_date
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    public void setSanDate(Date sanDate) {
        this.sanDate = sanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sanitation.labor_id
     *
     * @return the value of sanitation.labor_id
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    public Integer getLaborId() {
        return laborId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sanitation.labor_id
     *
     * @param laborId the value for sanitation.labor_id
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    public void setLaborId(Integer laborId) {
        this.laborId = laborId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sanitation.san_desc
     *
     * @return the value of sanitation.san_desc
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    public String getSanDesc() {
        return sanDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sanitation.san_desc
     *
     * @param sanDesc the value for sanitation.san_desc
     *
     * @mbggenerated Tue Apr 24 11:40:50 CST 2018
     */
    public void setSanDesc(String sanDesc) {
        this.sanDesc = sanDesc == null ? null : sanDesc.trim();
    }
}